myshop/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'
urlpatterns= [
    path('',views.cart_detail, name= 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace = 'coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/',include('aacount.urls')),
    path('', include('shop.urls', namespace = 'shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [
    path('social-auth/', include('social_django.urls', namespace='social')),
]

myshop/payment/urls.py
from django.urls import path
from . import views, webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name = 'process'),
    path('completed/', views.payment_completed, name = 'completed'),
    path('canceled/', views.payment_canceled, name = 'canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

myshop/payment/views.py
from _decimal import Decimal

import stripe
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from orders.models import Order

# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION
def payment_process(request):
    #order_id session key 가져오기
    order_id = request.session.get('order_id', None)
    # order_id 세션키로 현재 Order 객체를 데이터베이스에서 가져옴
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        success_url = request.build_absolute_uri(
            reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
            reverse('payment:canceled'))
        #Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id ,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [] #A list of items the customer is purchasing
        }
        # 주문 항목을 stripe checkout 세션에 추가
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency':'usd',
                    'product_data':{
                        'name':item.product.name,
                    },
                },

                'quantity': item.quantity,
            })
        # coupon apply
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name= order.coupon.code,
                percent_off = order.discount,
                duration = 'once', # 1회성 사용임
            )
            # 쿠폰을 결제 세션에 연결
            session_data['discounts'] = [{'coupon':stripe_coupon.id}]

        # create stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        return redirect(session.url, code =303)
    return render(request, 'payment/process.html', {'order':order})

def payment_completed(request):
    return render(request, 'payment/completed.html')

def payment_canceled(request):
    return render(request, 'payment/canceled.html')

myshop/payment/templates/payment/canceled.html
{% extends 'shop/base.html' %}
{% block title %} 결제 실패 {% endblock %}
{% block content %}
<h1>결제 실패</h1>
<p>결제에 실패했습니다. </p>
{% endblock %}

myshop/payment/templates/payment/completed.html
{% extends 'shop/base.html' %}
{% block title %} 결제 완료 {% endblock %}
{% block content %}
    <h1>결제 완료 </h1>
    <p>결제가 성공적으로 처리되었습니다. </p>
{% endblock %}

myshop/payment/templates/payment/process.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %} 주문 결제 {% endblock %}
{% block content %}
    <h1>주문 요약 </h1>
    <table class="cart">
        <thead>
            <tr>
                <th>이미지</th>
                <th>상품</th>
                <th>가격</th>
                <th>수량</th>
                <th>총 가격</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>
                    <img src="{% if item.product.image %}{{item.product.image.url }}
                    {% else %}{% static 'img/no_img.png' %}{% endif %}" >
                </td>
                <td>{{item.product.name}}</td>
                <td>{{item.price}}</td>
                <td>{{item.quantity}}</td>
                <td>{{item.get_cost}}</td>
            </tr>
            {% endfor %}
            {% if order.coupon %}
                    <tr class="subtotal">
                        <td>Subtotal</td>
                        <td colspan="3"></td>
                        <td class="num">
                            ${{order.get_total_cost_before_discount|floatformat:2}}
                        </td>
                    </tr>
                    <tr>
                        <td>{{order.coupon.code}} coupon
                        ({{order.discount}}% off)</td>
                        <td colspan="3"></td>
                        <td class="num neg">
                            -$ {{order.get_discount|floatformat:2}}
                        </td>
                    </tr>
                {% endif %}
                <tr class="total">
                    <td colspan="3">Total</td>
                    <td class="num">${{order.get_total_price_after_discount}}</td>
                </tr>
        </tbody>
    </table>
<form action="{% url 'payment:process' %}" method="post">
    <input type="submit" value = '지금 결제하기'>
    {% csrf_token %}
</form>
{% endblock %}