myshop/aacount/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import CustomLoginView, profileView

app_name='account'
urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(next_page='shop:product_list'), name='logout'),
    path('profile/',profileView.as_view() , name='profile')
]

myshop/cart/urls.py
from django.urls import path
from cart import views

app_name='cart'
urlpatterns= [
    path('',views.cart_detail, name= 'cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name= 'cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name= 'cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace = 'coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/',include('aacount.urls')),
    path('', include('shop.urls', namespace = 'shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += [
    path('social-auth/', include('social_django.urls', namespace='social')),
]

myshop/shop/urls.py
from django.urls import path, re_path
from . import views

app_name='shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    re_path(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique = True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args = [self.slug])

class Product(models.Model):
    # 카테고리 하나에 여러 제품 등록 될 수 있음 1(category):다(product)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import CartAddProductForm


# Create your views here.
def product_list(request, category_slug = None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available = True)

    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        products = products.filter(category = category)

    return render(request, 'shop/product/list.html',
                  {'category':category,
                   'categories':categories,
                   'products':products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug , available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                  {'product':product,
                   'cart_product_form':cart_product_form})

myshop/shop/templates/shop/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My shop {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div id="header">

        <a href="/" class="logo">My shop</a>

    {% if request.user.is_authenticated %}
    {{request.user}}님 <a href="{% url 'account:logout' %}"> logout</a>
    {% else %}
    <a href="{% url 'account:login' %}">login</a>
    {% endif  %}
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if total_items > 0 %}
             Your cart:
            <a href="{% url 'cart:cart_detail' %}">
                {{ total_item}} item {{total_item|pluralize}} ,
                ${{ cart.get_total_price}}
            </a>
            {% elif not order %}
                Your cart is empty.
            {% endif%}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>